### ISSUE TITLE
`oprofile` not found

### ISSUE THREAD

**Issue by AsyaKarpova** [Hemken/Statamarkdown#1]
I try to compile Rmd file with stata chunks with option `eval=FALSE`. 
This results in error with message `oprofile` not found.
I use StataMP 13

**Comment by Hemken** [comment]
Can you send me an example document that produces this error?

**Comment by AsyaKarpova** [comment]
[There is an example.](https://github.com/AsyaKarpova/Econometrics-Rosetta-Stone/blob/master/Simple/minimal_example.Rmd)

By now I`ve found that the error with message `oprofile` not found arrises when I compile the file from my bookdown project. 
But if I do it from another folder, I can compile the Rmd file with `eval=TRUE`, using Stata-64. With Stata-32 file is compiled with `eval=FALSE` (with `eval=TRUE` I have to close Stata manually and the stata chunk does not perform).

**Comment by Hemken** [comment]
I can look into the bookdown problem.

can you tell me the results of

packageVersion("Statamarkdown")
packageVersion("knitr")

find_stata() ought to be able to find the executable with the path shown in your example.  Both executables are on the same computer?

Have you run this Stata code in both versions of Stata manually?

**Comment by AsyaKarpova** [comment]
packageVersion("Statamarkdown")
`0.3.4`
packageVersion("knitr")
 `1.20`

Yes, both executables are on the same computer. I have changed the path to use Stata-64. 

If I run the code in both versions of Stata manually, it performs without problems.

**Comment by Hemken** [comment]
I have not been able to reproduce this problem.

I am using Statamarkdown 3.5, knitr 1.22, bookdown 0.9 .

**Comment by Hemken** [comment]
What YAML are you using?

**Comment by Hemken** [comment]
Conflict likely due to having two Stata versions.  No response to last questions ....
