### ISSUE TITLE
Possible problems with output from the display command in a stata chunk

### ISSUE THREAD

**Issue by remlapmot** [Hemken/Statamarkdown#14]
I think I notice that

* a stata chunk with a single `display` command produces no output
* a stata chunk starting with a blank line followed by a `display` command produces output as expected
* a stata chunk starting with a `display` command followed by subsequent `display` commands omits the output from the first `display` command.

An example Rmd file is below - pdf output attached 
[stmd-test.pdf](https://github.com/Hemken/Statamarkdown/files/5621596/stmd-test.pdf)

I am not sure where the error is for these, and maybe there are 2 or more little errors.

I tried to investigate

* at the end of `stata_engine()`, I included a 
`print(knitr::engine_output(options, options$code, out))`
and that looks ok to me. 

* when I include a `print(x)` at the beginning of `stataoutputhook()` there looks to be an issue relating to how character strings are parsed/joined, maybe because the `display` output includes string quotes.

* I also wondered if there was a second small error for the loss of the single/first line, and was wondering if the `firsttext` code has a problem because I see the warning
```
Warning messages:
1: In min(grep("[[:alnum:]]", y)) :
  no non-missing arguments to min; returning Inf
```

I have Stata 15.1 (but don't think this is anything to do with the Stata version).

Sorry I can't propose fixes.

Example Rmd file code
````
---
title: "display command output examples"
output: pdf_document
---

```{r setup}
# remotes::install_github("hemken/statamarkdown")
library(Statamarkdown)
library(sessioninfo)
```

Output for this chunk is missing
```{stata}
display "Hello 1"
```

Output correctly displayed with the first blank line removed
```{stata}

di "Hello 2"
```

Output from the first command omitted
```{stata}
di "Hello 3"
di "Hello 4"
```

Checking if these occur without the use of string quotes in the command

```{stata}
display 1
```

```{stata}

di 2
```

```{stata}
di 3
di 4
```

```{r}
sessioninfo::session_info()
```
````

**Comment by Hemken** [comment]
Thanks for the heads up

**Comment by Hemken** [comment]
Well, you’ve demonstrated that it’s not the quotes, and I can tell you that the problem is prior to the output hook.

**Comment by Hemken** [comment]
A quick work around is to have a profile.do (even an empty one).  The deeper problem lies back in knitr, so I will have to get Yihui to modify a line or two of code (that I contributed – my error!)

**Comment by remlapmot** [comment]
that's brilliant - thanks

**Comment by Hemken** [comment]
Resolved in an upcoming update to knitr

**Comment by remlapmot** [comment]
Thanks indeed - I tested with the development version of knitr with your commit and this is fixed.

**Comment by Hemken** [comment]
Thanks for closing this, I hadn't gotten around to testing this specific report myself.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
