### ISSUE TITLE
Update to RStudio version 1.4.1106 causes "play" button to disappear

### ISSUE THREAD

**Issue by momozinho** [Hemken/Statamarkdown#15]
Hi,

I have been successfully using `Statamarkdown` for a couple of months - and it's been super useful - so thanks!

I updated both R (R version 4.0.4) and RStudio (version 1.4.1106), which unfortunately has caused the "Run current chunk" or "play" button to disappear.

The document knits fine, it is just that I cannot run individual chunks in my Rmd file, nor can I run all chunks above/below if there are Statamarkdown chunks.

I tried to reinstall earlier version of both R (R version 3.6.3 - but `Statamarkdown` not supported) and RStudio (version 1.3.1093 - but problem remains).

I also tried to solve the issue by following advice from [RStudio issue #6220](https://github.com/rstudio/rstudio/issues/6220), but I get an error message:

> `sysuse auto`
`Error: unexpected symbol in "sysuse auto"
`

I would greatly appreciate your help in trying to find a solution.

Thanks,

Mo

**Comment by Hemken** [comment]
As far as I can tell, this is an RStudio issue, not a Statamarkdown issue.

**Comment by remlapmot** [comment]
Just to say I am on RStudio 1.4.1106 and R 4.0.4 on Windows and do not see any problems, e.g.

![image](https://user-images.githubusercontent.com/3777473/111335131-0ac1e000-866c-11eb-8190-38980c843153.png)

What operating system are you on?

**Comment by momozinho** [comment]
Thank you both for your replies.

Indeed @Hemken is right - it is not a Statamarkdown issue.

@remlapmot: FYI I am using MacOS

I found the origin of problem. I had changed the RMarkdown editor options `chunk_output_type` from `inline` to `console` in an attempt to prevent RStudio from freezing when I opened the the .Rmd file. When I did that, not only did the "Run Current Chunk" (play button) disappear, but running chunks above/below that included Statamarkdown chunks were not executed due to an error message:

`> cd "/path [...]"`
`Error: unexpected string constant in "cd "/path [...]" `
and
`> do [...].do`
`Error: unexpected symbol in "do [...]"`

When I revert to `chunk_output_type: inline` the problem disappears and I can use "Run Current Chunk" appropriately.

@Hemken: Would you prefer that I change the title of the issue to reflect the nature of the problem for future users?

Thanks,

Mo

**Comment by Hemken** [comment]
I think having “`play’ button disappear” in the title and your notes will help people who are searching the internet for this issue, so I would just leave it as is.  Thanks for letting me know!
