### ISSUE TITLE
Stata engine is located, but no output shown

### ISSUE THREAD

**Issue by drsapphire** [Hemken/Statamarkdown#16]
I have already installed Statamarkdown on R, and have already located my Stata engine. Then, i followed the examples, but i even cannot get the output of sysuse auto. I can knit the html as well as word document. But there is no output apart from my codes there. I am a MacOS (version 11.2.3) user. Please kindly help me

**Comment by Hemken** [comment]
Can you send me the markdown document?

**Comment by Hemken** [comment]
No response
