### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by kvenkita** [Hemken/Statamarkdown#20]
I'm trying to install the package and get the following error

> library(devtools)
Loading required package: usethis
> install_github("hemken/Statamarkdown")
Downloading GitHub repo hemken/Statamarkdown@HEAD
√  checking for file 'C:\Users\E-ITX\AppData\Local\Temp\RtmpcV3zgB\remotese383cd31ce8\Hemken-Statamarkdown-a68a8b9/DESCRIPTION' ...
-  preparing 'Statamarkdown':
E  checking DESCRIPTION meta-information ... 
   Malformed Depends or Suggests or Imports or Enhances field.
   Offending entries:
     Suggests: rmarkdown
   Entries must be names of packages optionally followed by '<=' or '>=',
   white space, and a valid version number in parentheses.
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.

Any help to resolve this is appreciated..

**Comment by Hemken** [comment]
I have not seen that error message before.

What versions of R, knitr, rmarkdown, and devtools are you using?

**Comment by Hemken** [comment]
I cannot reproduce that error

**Comment by MaraAlexeev** [comment]
I just got the same today with my first attempt at installing {Statamarkdown}.

**Comment by Hemken** [comment]
I am particularly interested in what version of R and what version of devtools you are using.
________________________________

**Comment by MaraAlexeev** [comment]
```
version  R version 4.0.2 (2020-06-22)
 ! package     * version date       lib source        
   devtools    * 2.4.0   2021-04-07 [1] CRAN (R 4.0.2)
```

**Comment by kvenkita** [comment]
R 4.0.4
devtools_2.4.2
knitr_1.33
rmarkdown 2.10

Thank you for looking into this!

**Comment by Hemken** [comment]
I **_am_** able to reproduce this error with
R 4.0.2 (haven't tried 4.0.4)
devtools 2.4.2 (it has so many dependencies it would take a lot of work to go back to 2.4.0)

I have no error when I use R 4.1.0 (I haven't upgraded past there yet, personally) and devtools 2.4.2

(I see the install_github() function has actually been moved to package "remotes" now.)

I'd suggest either upgrading R, or installing an older version of the Statamarkdown package (I have some older versions archived from Nov 2020, so not too old).

Let me know if that works or not.

**Comment by Hemken** [comment]
Note to self:  the email from GitHub did not include all the session info that Mara so nicely included in her original email.  Sorry I missed that!

**Comment by MaraAlexeev** [comment]
I updated to 4.1.0 and all is well. Sifting through the documentation to understand it all. Thanks for the package!

**Comment by kvenkita** [comment]
Thank you, it worked for me as well!
