### ISSUE TITLE
Stata output formatting issues.

### ISSUE THREAD

**Issue by MaraAlexeev** [Hemken/Statamarkdown#22]
Funny little thing I noted today while using the great {Statamarkdown} package. 

It seems like some of the Stata output gets cut off when running in an Rmarkdown document, and in a knitted document dependent on spacing in the code chunk. The the top of the Stata code output in Rmarkdown is always cut off, but in the knitted word output, it looks fine *if* there is a empty line at the top of the code chunk before the Stata command. 

Output cut off in Rmarkdown doc: 
![image](https://user-images.githubusercontent.com/39673697/137391928-8a6c12a4-c879-4a70-903d-1c9dae2b617e.png)

Output normal in knitted word doc from same Rmd: 

![image](https://user-images.githubusercontent.com/39673697/137392041-4bba47fe-4f13-4d69-8d01-a6d736552466.png)

Cut off exposure status headers in word doc when no space in code chunk:
![image](https://user-images.githubusercontent.com/39673697/137392168-a0c5f654-502f-4b38-9fac-4c316f85eab5.png)

Knit word output here: 

[github_issue.docx](https://github.com/Hemken/Statamarkdown/files/7349255/github_issue.docx)

Rmd text here (sorry cannot attach .Rmd extensions): 

[rmd_text_for_github_issue.txt](https://github.com/Hemken/Statamarkdown/files/7349289/rmd_text_for_github_issue.txt)

----
My session information: 

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Statamarkdown_0.7.0

loaded via a namespace (and not attached):
 [1] compiler_4.1.1  fastmap_1.1.0   htmltools_0.5.2 tools_4.1.1     yaml_2.2.1      rmarkdown_2.10 
 [7] knitr_1.33      digest_0.6.27   xfun_0.25       rlang_0.4.11    evaluate_0.14
```

**Comment by Hemken** [comment]
Currently traveling - it will be a week or two before I really address this issue.

I think this is the same as issue #14.  Try the work around of having a profile.do in your working directory?  (And let me know if that works - that will help me figure out if it is the same issue.)

**Comment by Hemken** [comment]
Fixed with upcoming change to knitr.
