### ISSUE TITLE
Loops and Collectcode

### ISSUE THREAD

**Issue by kvenkita** [Hemken/Statamarkdown#23]
Should loops in stata code be strictly contained within a code chunk in the rmd? In other words, will collectcode=True option allow parts of a loop to be split in multiple chunks?

Context: I split parts of the loop in different chunks and it failed.

**Comment by Hemken** [comment]
I don't think there is any way to do this.  If you try to place a partial loop in a profile.do, Stata finishes the profile.do with an error and tells you it came to an unexpected end of file.  Then the second chunk also gives you an error on " } ".
