### ISSUE TITLE
Statamarkdown fails to include output when run from a folder containing a space - MacOS

### ISSUE THREAD

**Issue by timothydobbins** [Hemken/Statamarkdown#24]
When running a Statamarkdown file stored in a MacOS path that contains a space, no Stata output is included. All Markdown and Stata code is included and formatted correctly, but no Stata output is included.

The problem is solved by running the file from a path with no spaces. Also, the issue does not appear when running in Windows.

I think that this issue may relate to the issue described in #13. My OneDrive for Business path includes a (non-removable) space, so Statamarkdown files cannot be run from my OneDrive.

A clue: the working directory contains a small log file called OneDrive.log consisting only of the lines:

```
Running /Users/td/OneDrive - UNSW/Software/RMarkdown/Statamarkdown/profile.do ...

file /Users/td/OneDrive.do not found
r(601);

```

It looks like this could be fixed by quoting the path so that the spaces could be incorporated, but I couldn't work how this could be done in the Statamarkdown code.

**Comment by Hemken** [comment]
This has been fixed.  It involved both a bug fix by Stata Corp. as well as a modification in Statamarkdown.
