### ISSUE TITLE
Ubuntu 18.04 installation issue

### ISSUE THREAD

**Issue by Lio21** [Hemken/Statamarkdown#3]
library(devtools) # before this you may need to install devtools
install_github("hemken/Statamarkdown")

Downloading GitHub repo hemken/Statamarkdown@master
✔  checking for file ‘/tmp/RtmpDK3s0n/remotes292552702801/Hemken-Statamarkdown-4581096/DESCRIPTION’ ...
─  preparing ‘Statamarkdown’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Statamarkdown_0.3.8.tar.gz’
   
Installing package into ‘/home/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
* installing *source* package ‘Statamarkdown’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning: l'exécution de la commande ''which' stata' renvoie un statut 1
Stata found at 
Warning: l'exécution de la commande ''which' stata' renvoie un statut 1
Error: package or namespace load failed for ‘Statamarkdown’:
 .onAttach failed in attachNamespace() for 'Statamarkdown', details:
  call: if (file.exists(file.path(dirname(find_stata(message = FALSE)), 
  error: l'argument est de longueur nulle
Erreur : le chargement a échoué
Exécution arrêtée
ERROR: loading failed
* removing ‘/home/R/x86_64-pc-linux-gnu-library/3.4/Statamarkdown’
Error in i.p(...) : 
  (converti depuis l'avis) installation of package ‘/tmp/RtmpDK3s0n/file292548567b2c/Statamarkdown_0.3.8.tar.gz’ had non-zero exit status
De plus : Warning message:
In is.na(remote_deps$package) :
  is.na() appliqué à un objet de type 'NULL' qui n'est ni une liste, ni un vecteur

**Comment by Hemken** [comment]
Is Stata installed on the server where you are installing this package?

Doug Hemken

**Comment by Lio21** [comment]
Yes, Stata and R are installed on the same machine. 
I have tested on another machine (also in Ubuntu 18.04), with the same result.

**Comment by Hemken** [comment]
Sorry for the slow response.

It appears not to find Stata when it is loaded.

When you type
which stata
On the *linux* command line, how does it respond?

This is what I see when I install:
> install.packages("~/R/Statamarkdown_0.3.8.tar.gz", type="source")
Installing package into ‘/home/h/hemken/R/x86_64-redhat-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
inferring 'repos = NULL' from 'pkgs'
* installing *source* package ‘Statamarkdown’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘Statamarkdown’
    finding HTML links ... done
    Statamarkdown-package                   html
    finding level-2 HTML links ... done

    find_stata                              html
    spinstata                               html
    stata_engine                            html
** building package indices
** installing vignettes
** testing if installed package can be loaded
Stata found at /usr/local/stata/stata
* DONE (Statamarkdown)

**Comment by Lio21** [comment]
when I type "which stata", I have:
/usr/local/stata15/stata

Le jeu. 6 juin 2019 à 19:01, Doug Hemken <notifications@github.com> a
écrit :

**Comment by Hemken** [comment]
Thank you.  I am able to reproduce the problem now.  I’ll work on this.

**Comment by Hemken** [comment]
I think this will install:

install.packages("https://www.ssc.wisc.edu/~hemken/Stataworkshops/Stata%20and%20R%20Markdown/Statamarkdown_0.3.9.tar.gz", type="source", repos=NULL)

**Comment by anhnguyendepocen** [comment]
When I tried
install.packages("https://www.ssc.wisc.edu/~hemken/Stataworkshops/Stata%20and%20R%20Markdown/Statamarkdown_0.3.9.tar.gz", type="source", repos=NULL)
 I get the following error:

================

Error: unexpected symbol in "Microsoft Windows"
Execution halted
ERROR: lazy loading failed for package 'Statamarkdown'
* removing 'C:/Users/anh nguyen/Documents/R/win-library/3.6/Statamarkdown'
Warning in install.packages :
  installation of package ‘C:/Users/anh nguyen/AppData/Local/Temp/RtmpIPyyMG/downloaded_packages/Statamarkdown_0.3.9.tar.gz’ had non-zero exit status

**Comment by Hemken** [comment]
I cannot reproduce this error.  Both the .zip and the .tar.gz versions install without error for me.  The symbol “Microsoft Windows” is not part of my source code.


-          Have you tried the .zip (binary) version instead of the .tar.gz (source) version?

-          Which Windows operating system are you using?

-          Which specific R version are you using?

**Comment by sagebiej** [comment]
Hey, I am facing the same problem as Lio21. I am running R on Ubuntu 18.04.  
The problem is obviously, that the package cannot locate the path of Stata (version 16).  In the command line, 
` which stata
/usr/local/stata16/stata
`

it seems fine. Also execute and read permission are provided for all users and the package `RStata` also works fine.

I tried `system2` directly in R (3.6.2)

`> system2("which", "stata", stdout = TRUE)
character(0)
attr(,"status")
[1] 1
Warning message:
In system2("which", "stata", stdout = TRUE) :
  running command ''which' stata' had status 1`

but others e.g. R work


`> system2("which", "R", stdout = TRUE) 
[1] "/usr/bin/R"`

Any ideas? 

Thanks a lot for the help. The package seems awesome and I cant wait testing it.

**Comment by Hemken** [comment]
Can you send me the error messages from R when you try to install?

**Comment by Hemken** [comment]
Another thought:

Is there any difference between:

linux> printenv PATH

and

R> system2(“printenv”, “PATH”)

**Comment by sagebiej** [comment]
> Can you send me the error messages from R when you try to install?

It is exactly the same as from Lio21


> Another thought: Is there any difference between: linux> printenv PATH and R> system2(“printenv”, “PATH”)

Yes, this is actually different

Terminal: 
```
julian@Tiger:~$ printenv PATH
/home/julian/bin:/usr/local/stata16:/usr/local/MATLAB/R2019b/bin:/home/julian/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

in R:
```
system2("printenv" , "PATH")
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```
So the PATH from R does not contain my Stata folder, which should explain the issue. 

In the meantime i found a workaround, which, however is not very elegant. I created a symbolic link in `/usr/bin` to my Stata folder, and put it at the very beginning of PATH. Then it worked. But not a very nice solution. 

Just as a suggestion. In the package RStata, you let R know where the Stata file is in the options(). And you can add it after package installation. This may also solve the problem.

**Comment by Hemken** [comment]
I agree with your suggestion.
My package tries to build vignettes, using Stata, when it is installed.  I see now this is a mistake, because if Stata is not found automatically the vignettes fail to build and the whole installation fails.  I need to go back to the older method of vignette building so that Stata is not needed for installation.  Once installed, one can always code in the Stata executable location, like with RStata.

**Comment by Crismoc** [comment]
I just would like to check, is there any solution for installing Statamarkdown when this happens? I have the same issue described above using Ubuntu 20.04. @sagebiej could you give a more detailed description of your workaround? Thanks!

**Comment by sagebiej** [comment]
The workaround is pretty easy. 



- [ ] check the content of the  PATH variable on the console in the linux command line: `printenv PATH`

- [ ] Check  the content of the PATH variable directly in R: `system2("printenv" , "PATH")`

- [ ]  If the differ, you have found the issue. If the do not differ, I think my workaround will not work.

- [ ] Create a symbolic link from the stata executable to (ideally the first) path that you found with `system2` in step 2. In the Linux command line, you type `ln -s location_of_stata location_in_PATH`. For example, I used `/usr/bin` 

- [ ] In my case this is `ln -s  /usr/local/stata16/stata /usr/bin/stata`

Hope that helps...

**Comment by Hemken** [comment]
Let me know whether or not this works, and if not, where Stata is located on your system

**Comment by Crismoc** [comment]
Great, thank you very much @sagebiej. The workaround works
