### ISSUE TITLE
Stata 18 has been released

### ISSUE THREAD

**Issue by remlapmot** [Hemken/Statamarkdown#36]
Hi Doug

I see that Stata 18 has been released this week <https://www.stata.com/>.

I don't have a copy yet myself but I think there are a few filepaths we can add the 18 version of to in `R/find_stata.r` for this.

**Comment by Hemken** [comment]
Oh, thanks for pointing that out.  It will likely be a few weeks before our dear institution makes that available.

Doug Hemken

Statistical consultant
Social Science Computing Cooperative
Univ. of Wisc. – Madison

***@***.******@***.***>
608-262-4327

From: Tom Palmer ***@***.***>
Sent: Thursday, April 27, 2023 12:44 PM
To: Hemken/Statamarkdown ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hemken/Statamarkdown] Stata 18 has been released (Issue #36)


Hi Doug

I see that Stata 18 has been released this week https://www.stata.com/.

I don't have a copy yet myself but I think there are a few filepaths we can add the 18 version of to in R/find_stata.r for this.

**Comment by Hemken** [comment]
I have updated Statamarkdown to recognize Stata 18, but I am not yet able to test this.  (I just needed to change the search for the executable to include version 18 for Windows.)  I’ll defer putting this on CRAN until I can test it properly.

**Comment by remlapmot** [comment]
That's great Doug

On line 46 of find_stata.r I think it would be worth adding `"/usr/local/stata18"` to the Linux filepaths as well.

It will also take my University several months to upgrade to Stata 18.

Also it's probably worth waiting for Yihui to release the next version of knitr on CRAN before making the next release. Because knitr 1.43 will have your commits in, so you could set the requirement of `knitr (>= 1.43)` in the `DESCRIPTION` file once knitr 1.43 is on CRAN.

**Comment by Hemken** [comment]
Ah yes!  Thanks for catching that.

Doug Hemken

Statistical consultant
Social Science Computing Cooperative
Univ. of Wisc. – Madison

***@***.******@***.***>
608-262-4327

**Comment by Hemken** [comment]
Unix done

Doug Hemken

Statistical consultant
Social Science Computing Cooperative
Univ. of Wisc. – Madison

***@***.******@***.***>
608-262-4327

**Comment by remlapmot** [comment]
Great - thanks Doug
