### ISSUE TITLE
Problems with instalation. 

### ISSUE THREAD

**Issue by Wario84** [Hemken/Statamarkdown#7]
I have problems installing the package, here:

`> devtools::install_github("Hemken/Statamarkdown")
Downloading GitHub repo Hemken/Statamarkdown@master
✔  checking for file ‘/tmp/RtmpEuzkGc/remotes1b707aa350e9/Hemken-Statamarkdown-0457a3a/DESCRIPTION’ ...
─  preparing ‘Statamarkdown’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Statamarkdown_0.3.9.tar.gz’
   
Installing package into ‘/home/mariogs/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package ‘Statamarkdown’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Warning in system2("which", "stata", stdout = TRUE) :
  running command ''which' stata' had status 1
Stata found at 
Error: package or namespace load failed for ‘Statamarkdown’:
 .onAttach failed in attachNamespace() for 'Statamarkdown', details:
  call: if (stataexe != "") {
  error: argument is of length zero
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/mariogs/R/x86_64-pc-linux-gnu-library/3.6/Statamarkdown’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/RtmpEuzkGc/file1b701622620d/Statamarkdown_0.3.9.tar.gz’ had non-zero exit status
> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes          

`

**Comment by Hemken** [comment]
Mario,
Three questions:
- if you type “which stata” at a Linux command prompt, what response does the system give you?
- do you know where Stata is actually installed on your system?
- which flavor of Stata?  (IC, SE, MP ?). I’m assuming a fairly recent version?

Doug Hemken
________________________________

**Comment by Wario84** [comment]
Hi Dough,

My Stata is version IC, and I get the following output:

![Screenshot from 2019-09-11 14-27-31](https://user-images.githubusercontent.com/18721051/64697223-a0d9e080-d4a0-11e9-85bf-9cfa93ed025e.png)

Thanks for your help.

Mario
