### ISSUE TITLE
undesired output when `collectcode=TRUE`

### ISSUE THREAD

**Issue by filius23** [Hemken/Statamarkdown#9]
As documented, `collectcode=TRUE` is a chunk option that helps collecting Stata code across chunks. 

While this works neatly, the outputs of the second (and any further) chunks follwing the first with `collectcode=TRUE` contain an undesired echo at the top:
> Running .......\profile.do

For instance, when running a second chunk with `{stata stata2, echo = T,collectcode=TRUE}`

 ```{stata stata2, echo = T,collectcode=TRUE}
    reg mpg price i.foreign ,  noheader  
 ```
yields this output:

    reg mpg price i.foreign ,  noheader  
    Running C:\Cloud\Methods\prog\profile.do . reg mpg price i.foreign ,  noheader  
    ------------------------------------------------------------------------------
             mpg |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
    -------------+----------------------------------------------------------------
           price |   -.000959   .0001815    -5.28   0.000     -.001321    -.000597
                 |
         foreign |
        Foreign  |   5.245271   1.163592     4.51   0.000     2.925135    7.565407
           _cons |   25.65058   1.271581    20.17   0.000     23.11512    28.18605
    ------------------------------------------------------------------------------

Here's my RMarkdown repex:

    ---
    title: "Statamarkdown output problem"
    output: html_document
    ---
    
    ```{r setup, include = F}
    library(Statamarkdown)
    ```
    
    
    First chunk is clean:
    
    ```{stata stata1,collectcode=TRUE}
    sysuse auto
    su mpg price
    ```
    
    Second Stata Output contains undesired `Running .......\profile.do` output:
    
    ```{stata stata2, echo = T,collectcode=TRUE}
    reg mpg price i.foreign ,  noheader  
    ```
    
    Problem persists even in chunks with `collectcode=FALSE`:
    
    ```{stata new_data, echo = T,collectcode=F}
    webuse bpwide, clear
    su sex agegrp
    ```
    
    `cleanlog = F` does not do the trick:
    ```{stata new_data2, echo = T,collectcode=F, cleanlog = FALSE}
    webuse bpwide, clear
    su sex agegrp
    ```

Avoiding `collectcode=T` alltogether, i.e. load and preparing the data for each chunks would of course be a workaround, but extremely tedious.

I also posted a SO question [here](https://stackoverflow.com/questions/63284332/rmarkdown-statamarkdown-produces-undesired-output-when-collectcode-true), in case it's more a misunderstanding on my part rather than a bug.
Any idea/help is very much appreciated! 
Thank you very much for this very useful package!

**Comment by philippleppert** [comment]
I have the same issue and created a pull request to modify `stataoutputhook.R`. This function is looking for the pattern "Running ...." displayed by Stata output. However, older versions of Stata (I use 14) display "running ..." instead of "Running .. " so the line is not removed from the RMarkdown output. I think the function should take into account both cases to ensure full compatibility with older and newer versions of Stata.
